travis:
  secure:
    BINSTAR_TOKEN: sX97SrBd6epb0cjwoh7OfSkASDUIug/DBKedusm9KIjXYj6Q4d9pZrz3xhAQDfz2kY7Cz8tMks529V1COLHOpLM2w3l63XLhEq4/EjXrjQ25jgaJ6lTJ0C7mtvtNjJWC8aFMwRrxi1Qavt+MrQFBfCaK1SJHTi4OT4z9y5FTmb4cqkWdtmoBHTWXnnIZ+thdjnJ5j06wOKLAVn576ml4hyCg+3ZMGChZFjpi/1DTdFemp25+jVojVKlrkrdWvZlc8iushKy4hIveNlM2BrlT42Hk54Bx6m+tkJ71MUDUtTEwveP5B25t2MEH3ps7PKP63pnw/fd1TCzbdX4M9wRJi0uhfxhhll1EQOygSdhyGj2EAuECOdbE1jYVIwFKPBi9oGmzpJVyRsq1t4hf56vUn2EavubMwJbFtSd9oyJTNff6U/Nmr+xvP5M5Q+Ui5D5I00GcB/EwT7l20kDuu2oStM8yd2hN0CTgUQzPal9MPdAAq1AQDp+TSr5gAaQ5ud2hTm8/KLIMVoGMbXhM0Un1EbZPFvPGOz90n0FH6isIJZQb63o7MqU3J7dfsWTrm3kS0QXJ52vCkLmesiCCHSnlhm4unx44BbcxdW6ajpKStSfKWcN+c3XH6rqW8adUbmqqv+fsEGAne2d2uCGPUFK2R+JKowEU6XLYUBaaudj0hiA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
