travis:
  secure:
    BINSTAR_TOKEN: nEbMJOkzqnvM7aZN7HbiaQ3n0iv9jqt9WcVg2HZkRw+N/n7dc7z0zR7v15dy26ARgi6QHPv+mfNu5wUU/znHOckEZFs9IDrV6ZOMpU3xgoYw6FEPllykQxLs9GGjTjZJDKkB5xmZHjKWs7OyWu+nctJU1yAXJYLHMmGSfwU728xVhy3LjOYD8cHXbk7IUnvDXgA6LKAgfkmSS0KaeJ/Edpg/NymrRtd+uWdZWBrHc+SOFC4r4DmR6x1POQHAmrTeQktcF8M+Uz7vwpNb6Jo2ggRLQ6n9xxiPIECU/RPMhCVsZBVguqgiJzRZgBHeu4opN9l7v7/TOMsWkSWjSuhdS8SqaMitMvFk52NR+LpEcqmeZS04Jbuq+tR7EqIkoG8aaX6PRCwee6bWtxExesGm4Y0WlluVv8ia6Eo2vQGmbjf1UCqpscijnz0Ey7xnFu9JcmvIG5pNy9SYTcio/aJAgIYC5Au+0E9ZzDQI1OE61OOThD3jfb8DUKUHuTImRKMe+6WGG6mKTJJHf5WLjI6KxANNv2MvK229sXUplZGbRm01v8zQzPERNWqK5qSBKObJe9XyCyy/uX8M8+9qwkkypiDg/YavWqvJT+BJfpx+1UYWfb9Ern8teSm+J5G+Iw1xF3/IjoQs/2zpT1FmEt6ED7yFoozjzGhCfeMe7+fZw+Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
